###Testing server status
GET http://localhost:8000/

// --------------------------------- Task Routers Below------------------------------------
### Get all the task from api
GET http://localhost:8000/api/v1/task

### Post the task to api
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task":"Sleeping",
    "hour":"33",
    "type":"entry"
}

### Update the task at api
PATCH http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "_id":"64850a4d9e87e5f7dff02760",
    "type":"bad"
}



### Delete the task from api
DELETE  http://localhost:8000/api/v1/task/6485083ede3ce5850eeda672












// To Dos

